### ISSUE TITLE
retro template not found from bash script

### ISSUE THREAD

**Issue by atharvapurdue** [connorcoley/ASKCOS#42]
Do we need to change the bash script ?
The retro template and forward template are not loaded even after I change the bash script path to local database.
(In makeit folder, git clone askcos data repo)

![image](https://user-images.githubusercontent.com/31735343/109938926-8def4780-7cf6-11eb-8c77-c3e640410642.png)

**Comment by mliu49** [comment]
Hi @sparklytopaz, could you provide some more details to help identify the cause of the issue?
- Are you using the latest master branch of ASKCOS?
- Did you build your own docker image, or are you using the image from Docker Hub?
- What was the deploy.sh command that you ran?

**Comment by atharvapurdue** [comment]
hi @mliu49, sure  :-
yes I am using the latest master branch of ASKCOS
I did the following : 
```
git clone https://github.com/ASKCOS/ASKCOS
```
```
$ cd ASKCOS/makeit
$ git clone https://github.com/ASKCOS/askcos-data data
```

```
cd ..
docker build -t askcos/askcos .
cd deploy
bash deploy.sh deploy
```
the nginx gives a gateway error 504

**Comment by mliu49** [comment]
Thanks, there is one likely issue that stands out: for building the docker image, you do not need to clone askcos-data at the `makeit/data` location. During the docker build process, askcos-data is automatically downloaded from Docker Hub (the askcos/askcos-data image).

However, the reason why that would cause problems is that git-lfs was likely not set up while cloning askcos-data. That would result in many of the data and model files being missing (since they would only be lfs pointer files). Missing data would cause the database seeding error, and missing models could cause the gateway error.

If you do not need to make source code modificiations, I suggest directly downloading the askcos image from Docker Hub (`docker pull askcos/askcos`). If you prefer to build your own image, you should delete the `makeit/data` directory and run `docker build -t askcos/askcos .` again.

**Comment by atharvapurdue** [comment]
Thanks !
I deleted the makeit/data directory and ran 
```
docker build askcos/askcos . 
```
and then 
```
cd deploy
bash deploy.sh deploy
```
but i am still getting this issue
also git lfs is not pulling anything for me
I will create another conda env for askcos v4 and try again , if you could suggest me anything else , that would be helpful!

**Comment by mliu49** [comment]
FYI, you do not need to create a conda environment if you are deploying using docker. The docker containers are isolated from your local conda environment.

It's possible that there is data which was not fully cleaned up from your previous deploy attempts. You should run `docker-compose down -v` from the deploy directory before running `bash deploy.sh deploy` again.

**Comment by atharvapurdue** [comment]
yes cleaning previous deployment attempts worked partially
the retro templates are downloaded but the forward template download is throwing an error.
and i am getting a server error (500) 
Thanks for the help @mliu49 ! 
![image](https://user-images.githubusercontent.com/31735343/110000317-27d7e400-7d39-11eb-8b94-0245ad4fdcbb.png)

**Comment by mliu49** [comment]
Can you confirm whether you've made any changes to the deploy.sh script? Your log shows an error saying that the `/data/app/templates/default.gz` file does not exist; however, that is not the file that should be loaded: https://github.com/ASKCOS/ASKCOS/blob/master/deploy/deploy.sh#L238

**Comment by atharvapurdue** [comment]
Thank you so much @mliu49 
The problem has be solved
